using Constructor5.Elements.TestConditions;
using Constructor5.UI.AutoGeneratedEditors;
using Constructor5.Xml;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Constructor5.Elements.SituationGoals.Components
{
    [XmlSerializerExtraType]
    [HasAutoEditor("These conditions must pass in addition to the goal for it to count.")]
    public class SituationGoalPostConditionsComponent : SituationGoalComponent
    {
        public override string ComponentLabel => "Post Conditions";

        [AutoEditorConditionList]
        public ObservableCollection<TestConditionListItem> Conditions { get; set; } = new ObservableCollection<TestConditionListItem>();

        protected internal override void OnExport(SituationGoalExportContext context)
        {
            var conditions = new List<TestCondition>();
            foreach (var condition in Conditions)
            {
                conditions.Add(condition.Condition);
            }

            TestConditionTuning.TuneTestConditions(context.Tuning, conditions, "_post_tests");
        }
    }
}
