using Constructor5.Base.ElementSystem;
using Constructor5.Base.ExportSystem.Tuning;
using Constructor5.Base.ExportSystem.Tuning.Utilities;
using Constructor5.Elements.LootActionSets;
using Constructor5.Elements.TestConditions;
using Constructor5.Elements.Traits;
using Constructor5.UI.AutoGeneratedEditors;
using Constructor5.UI.Shared;
using Constructor5.Xml;
using System;

namespace Constructor5.Elements.Buffs.Components
{
    [XmlSerializerExtraType]
    [SharedWithTraits]
    [HasAutoEditor("These actions will run every 10 Sim minutes (unless configured in Advanced Settings). A common use is to check the conditions of a Sim (such as which interaction they're currently performing or which venue they're in) and apply a buff based on those conditions.")]
    public class BuffLootComponent : BuffComponent
    {
        public override string ComponentLabel => "Actions";

        [AutoEditorReferenceList("LootActionSet", "BuffLootItem", ShowCreateButton = true)]
        public ReferenceList LootActionSets { get; set; } = new ReferenceList();

        protected internal override bool HasContent() => LootActionSets.HasItems();

        protected internal override void OnExport(BuffExportContext context)
        {
            foreach (var set in LootActionSets.GetOfType<BuffLootItem>())
            {
                if (set.RunOnInterval)
                {
                    TuneRunOnInterval(context, set);
                }

                if (set.RunOnInstance)
                {
                    context.Tuning.Get<TunableList>("_loot_on_instance").Set<TunableBasic>(null, set.Reference);
                }

                if (set.RunOnAddition)
                {
                    context.Tuning.Get<TunableList>("_loot_on_addition").Set<TunableBasic>(null, set.Reference);
                }

                if (set.RunOnRemoval)
                {
                    context.Tuning.Get<TunableList>("_loot_on_removal").Set<TunableBasic>(null, set.Reference);
                }
            }

            foreach (var commodityTuning in context.IntervalCommodities.Values)
            {
                TuningExport.AddToQueue(commodityTuning);
            }
        }

        private void TuneRunOnInterval(BuffExportContext context, BuffLootItem set)
            => TuneRunOnInterval(context, set.IntervalMin, set.IntervalMax, set.Reference);

        private void TuneRunOnInterval(BuffExportContext context, int intervalMin, int intervalMax, Reference reference)
            => BuffLootOnIntervalBuilder.AddToCommodity(context, intervalMin, intervalMax, reference);
    }
}
