using Constructor5.UI.AutoGeneratedEditors;
using Constructor5.UI.Shared;
using Constructor5.Core;

namespace Constructor5.Elements.Situations.Components
{
    [XmlSerializerExtraType]
    [HasAutoEditor]
    public class SituationTemplateComponent : SituationComponent
    {
        public override int ComponentDisplayOrder => 2;
        public override string ComponentLabel => "Content";

        [AutoEditorSelectableObject("SituationTemplates")]
        public SituationTemplate Template { get; set; } = new DefaultSituationTemplate();

        protected internal override void OnExport(SituationExportContext context) => Template.OnExport(context);
    }
}