using System;
using System.Reflection;
using System.Windows;

namespace Constructor5.UI.AutoGeneratedEditors
{
    public abstract class AutoEditorAttribute : Attribute
    {
        public abstract UIElement CreateControl(object obj, PropertyInfo prop);
    }
}