using Constructor5.UI.Shared;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using TextBlock = Constructor5.UI.Shared.TextBlock;

namespace Constructor5.UI.AutoGeneratedEditors
{
    public class AutoGeneratedEditor : IObjectEditor
    {
        object IObjectEditor.Content => AutoContent;

        void IObjectEditor.SetObject(object obj, string tag)
        {
            var scrollViewer = new ScrollViewer
            {
                DataContext = obj,
                VerticalScrollBarVisibility = ScrollBarVisibility.Visible
            };

            var padding = (Thickness)Application.Current.FindResource("Constructor.BigPaddingMinusTop");

            var stackPanel = new StackPanel();
            scrollViewer.Content = stackPanel;

            var hasAutoEditorAttribute = (HasAutoEditor)obj.GetType().GetCustomAttribute(typeof(HasAutoEditor));
            if (hasAutoEditorAttribute.Text != null)
            {
                var textBlock = new TextBlock()
                {
                    Text = hasAutoEditorAttribute.Text,
                    TextWrapping = TextWrapping.Wrap
                };
                if (hasAutoEditorAttribute.HasPadding)
                {
                    textBlock.Padding = padding;
                }
                stackPanel.Children.Add(textBlock);
            }

            foreach (var prop in obj.GetType().GetProperties())
            {
                foreach (AutoEditorAttribute attribute in prop.GetCustomAttributes(typeof(AutoEditorAttribute), true))
                {
                    var control = attribute.CreateControl(obj, prop);
                    if (hasAutoEditorAttribute.HasPadding)
                    {
                        ((FrameworkElement)control).Margin = padding;
                    }
                    stackPanel.Children.Add(control);
                }
            }

            AutoContent = scrollViewer;
        }

        private object AutoContent { get; set; }
    }
}