using Constructor5.Base.ElementSystem;
using Constructor5.UI.Shared;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace Constructor5.UI.AutoGeneratedEditors
{
    public class AutoEditorReferenceWithEditorUnderneath : AutoEditorAttribute
    {
        public AutoEditorReferenceWithEditorUnderneath(string elementTypeName) => ElementTypeName = elementTypeName;

        public string ElementTypeName { get; set; }
        public ulong ResetTo { get; set; }
        public string ResetToLabel { get; set; }

        public override UIElement CreateControl(object obj, PropertyInfo prop)
        {
            var padding = (Thickness)Application.Current.FindResource("Constructor.BigPaddingMinusTop");

            var stackPanel = new StackPanel()
            {
                Margin = padding
            };

            var value = (Reference)prop.GetValue(obj);

            var objectEditor = new ObjectEditorControl
            {
                EditorCategory = "Default",
            };
            var refControl = new ReferenceControl
            {
                ElementTypeName = ElementTypeName,
                ResetTo = ResetTo,
                ResetToLabel = ResetToLabel,
                ShowCreateButton = true
            };
            refControl.ReferenceChanged += (reference) =>
            {
                objectEditor.Object = reference?.Element;
            };
            refControl.Reference = value;

            stackPanel.Children.Add(refControl);
            stackPanel.Children.Add(objectEditor);

            return stackPanel;
        }
    }
}