using Constructor5.UI.Shared;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;

namespace Constructor5.UI.AutoGeneratedEditors
{
    public class AutoEditorSelectableObject : AutoEditorAttribute
    {
        public AutoEditorSelectableObject(string typeRegistryCategory) => TypeRegistryCategory = typeRegistryCategory;

        public string TypeRegistryCategory { get; set; }

        public override UIElement CreateControl(object obj, PropertyInfo prop)
        {
            var padding = (Thickness)Application.Current.FindResource("Constructor.BigPaddingMinusTop");

            var stackPanel = new StackPanel()
            {
                Margin = padding
            };

            var value = prop.GetValue(obj);

            var editorControl = new ObjectEditorControl
            {
                EditorCategory = "Default",
                Object = value
            };

            var objectControl = new SelectableObjectControl
            {
                EditorCategory = "Invalid",
                TypeRegistryCategory = TypeRegistryCategory
            };
            objectControl.ObjectChanged += (newObject) =>
            {
                editorControl.Object = newObject;
                prop.SetValue(obj, newObject);
            };
            objectControl.Object = value;

            stackPanel.Children.Add(objectControl);
            stackPanel.Children.Add(editorControl);

            return stackPanel;
        }
    }
}