using Constructor5.Base.Startup;
using Constructor5.UI.Shared;
using System;

namespace Constructor5.UI.AutoGeneratedEditors
{
    public class HasAutoEditor : StartupTypeAttribute
    {
        public HasAutoEditor()
        {
        }

        public HasAutoEditor(string text) => Text = text;

        public bool HasPadding { get; set; } = true;
        public string Text { get; set; }

        public override void Invoke(Type type) => ObjectEditorManager.SetEditorType(type, typeof(AutoGeneratedEditor), "Default");
    }
}