using Constructor5.Base.ElementSystem;
using Constructor5.Base.ExportSystem.AutoTuners;
using Constructor5.Core;
using Constructor5.UI.AutoGeneratedEditors;

namespace Constructor5.Elements.LotTraits
{
    [HasAutoEditor("LotTraitExitActionsNotice")]
    [XmlSerializerExtraType]
    public class LotTraitExitActions : LotTraitComponent
    {
        public override string ComponentLabel => "ExitActions";

        [AutoEditorReferenceList("LootActionSet", ShowCreateButton = true)]
        [AutoTuneReferenceList("exit_lot_loot")]
        public ReferenceList LootActionSets { get; set; } = new ReferenceList();

        protected internal override void OnExport(LotTraitExportContext context)
            => AutoTunerInvoker.Invoke(this, context.Tuning);
    }
}