using Constructor5.UI.AutoGeneratedEditors;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Windows;

namespace Constructor5.Elements.TestConditions
{
    public class AutoEditorConditionList : AutoEditorAttribute
    {
        public override UIElement CreateControl(object obj, PropertyInfo prop) => new ConditionListControl
        {
            ConditionList = (IEnumerable<TestConditionListItem>)prop.GetValue(obj)
        };
    }
}
