using Constructor5.Core;
using Constructor5.Elements.Situations;
using Constructor5.UI.AutoGeneratedEditors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Constructor5.Elements.DramaNodes.Components
{
    [XmlSerializerExtraType]
    [HasAutoEditor]
    public class DramaNodeTemplateComponent : DramaNodeComponent
    {
        public override string ComponentLabel => "Content";

        [AutoEditorSelectableObject("DramaNodeTemplates")]
        public DramaNodeTemplate Template { get; set; } = new DefaultDramaNodeTemplate();

        protected internal override void OnExport(DramaNodeExportContext context) => Template.OnExport(context);
    }
}
