using Constructor5.Base.ElementSystem;
using Constructor5.UI.AutoGeneratedEditors;
using Constructor5.Core;

namespace Constructor5.SituationTemplates.SimpleSituation
{
    [XmlSerializerExtraType]
    [HasAutoEditor(HasPadding = false)]
    public class SimpleSituationJobItem : ReferenceListItem
    {
        [AutoEditorReference("RoleState", ResetTo = 99710, ResetToLabel = "Generic", Label = "Role State", HasPadding = false)]
        public Reference RoleState { get; set; } = new Reference(99710, "Generic");
    }
}